name: test-2bc233c04d9b-locnnil
version: "demo"
summary: test snap publish stuff
description: This is a snap to test snap store publishing features

grade: stable
base: core24
# confinement: strict
confinement: devmode

apps:
  env:
    command: usr/bin/exec-env

  hello:
    command: usr/bin/say-hello

parts:
  env:
    plugin: dump
    source: .
