name: build-publish

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Pull Request number to checkout'
        required: true
        type: number
      upload-to-store:
        description: 'Upload to a branch on snaptore?'
        required: true
        type: boolean

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        PR_NUMBER: ${{ github.event.inputs.pr-number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ env.$PR_NUMBER }}/merge

      - name: Build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: snap --output test-pr-${{ env.PR_NUMBER }}.snap

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-pr-${{ env.pr_number }}.snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Publish to Store branch
        if: "${{ github.event.inputs.upload-to-store == 'true' }}"
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge/pr-${{ env.PR_NUMBER }}

      - name: Generate Workflow config
        run: |
          printf '{
          "pr-number" : ${{ env.PR_NUMBER }}
          "uploaded-to-store" : ${{github.event.inputs.upload-to-store}}
          }' >> config.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: config.json
          path: ./

