name: manual

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run id'
        required: true
        type: number

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow_search: true
          name: test_${{ github.event.inputs.run_id }}.snap
          run_id: ${{ github.event.inputs.run_id }}

      - name: Publish to Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: test_${{ github.event.inputs.run_id }}.snap
          release: latest/edge/runid-${{ github.event.inputs.run_id }}


      - name: Install and run snap
        run: |

          sudo snap install test-2bc233c04d9b-locnnil --channel=latest/edge/runid-${{ github.event.inputs.run_id }}
          test-2bc233c04d9b-locnnil.hello2
