
name: simple-test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  check-pr-number:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Save event number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "PR_NUMBER-> $PR_NUMBER "

      - name: Get the artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: test_[0-9]+.snap
          name_is_regexp: true

      - name: Install and run snap
        run: |

          sudo snap install --dangerous test_*.snap
          test-2bc233c04d9b-locnnil.hello2

